name: Release

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Instalar dependências
        run: npm install

      - name: Rodar build
        run: npm run build

      - name: Testes unitarios
        run: npm test    
      #PARTE 1 - Até aqui

      #PARTE 2 - A partir daqui (descomentar)
      - name: Checkout do código
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Instalar semver
        run: npm install -g semver

      - name: Criar nova tag caso não exista
        id: create_initial_tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -z "$(git tag)" ]; then
            git config --global user.name 'luanzeraa-lab'
            git config --global user.email 'luansilvapicoli@gmail.com'
            git tag -a v0.0.0 -m "Initial release"
            git push origin v0.0.0
          fi

      - name: Calcular nova versão
        id: version
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="v0.0.0"
          fi
          
          echo "Versão atual: $LAST_TAG"

          CURRENT_VERSION=${LAST_TAG#v}
          NEW_VERSION=$(semver -i patch $CURRENT_VERSION)

          echo "Nova versão: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Atualizar versão no package.json
        run: |
          npm version ${{ env.new_version }} --no-git-tag-version

      - name: Commit e push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'luanzeraa-lab'
          git config --global user.email 'luansilvapicoli@gmail.com'
          
          if git diff --quiet package.json; then
            echo "Nenhuma mudança de versão"
          else
            git add package.json
            git commit -m "chore(release): version ${{ env.new_version }}"
            git tag v${{ env.new_version }}
            git push origin main --tags
          fi

      - name: Enviar email se pipeline falhar
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Pipeline falhou
          body: O pipeline do GitHub Actions falhou.
          to: ${{ secrets.EMAIL_USER }}
          from: GitHub Actions